org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.daemon=false
kotlin.compiler.execution.strategy=in-process
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.incremental=true
android.useAndroidX=true
android.nonTransitiveRClass=true
